# Base configuration
defaults: &defaults
  device: 'cuda'
  batch_size: 512
  epochs: 50
  model_dir: 'models/sl_collider'
  results_dir: 'results/sl_collider'

# Dataset configuration
dataset: &dataset
  func_name: 'bk_sl_collider'
  func_arg:
      alpha: 0.1
  grid_points: 3000
  kmin: 0.001
  #KZ NOTE: for slow-collider we don't need expansion since it doesn't peak at k=1
  kmax: 1.0 
  scale_invariant: true
  #KZ NOTE: version 2 should be more uniform around k2=1
  k2_sample_version: 2
  

# Experiments
experiments:
  test_1:
    <<: *defaults
    description: "simplest model with 1 term"
    model_params:
      num_terms: 1
      symm_kind: 2
      sub_arch: 'MLP'
    dataset_params_train:
      <<: *dataset
    dataset_params_vali:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0015
    dataset_params_test:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0013

  test_2:
    <<: *defaults
    description: "Model with 2 terms"
    model_params:
      num_terms: 2
      symm_kind: 2
      sub_arch: 'MLP'
    dataset_params_train:
      <<: *dataset
    dataset_params_vali:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0015
    dataset_params_test:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0013
      
  test_3:
    <<: *defaults
    description: "Model with 2 terms and more training "
    model_params:
      num_terms: 2
      symm_kind: 2
      sub_arch: 'MLP'
    dataset_params_train:
      <<: *dataset
      grid_points: 5000  # Different grid size
    dataset_params_vali:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0015
    dataset_params_test:
      <<: *dataset
      grid_points: 1000
      kmin: 0.0013